### PR TITLE
Fix compilation error due to argument name

### LINKED ISSUE #18: Compilation fails on Elixir 1.7.0-rc.1
Hi,

just to let you know: `prometheus_ex` (currently published version on Hex) seems to fail to compile on Elixir 1.7.0-rc.1 (OTP 20).

image

Might be related to https://github.com/elixir-lang/elixir/pull/7309
Would love to contribute a fix but I'm not terribly familiar with what the purpose of the Macro is in `prometheus_ex` :-/

### PR DESCRIPTION
**Pull request by jfornoff**
Fixes #18.

### CODE REVIEW

**Comment by deadtrickster** [comment]
Danke
